# Generated by Django 5.0.6 on 2024-06-26 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grau_perda', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grauperda',
            old_name='configuracao_audiometrica',
            new_name='grau_perda',
        ),
    ]
