# Generated by Django 5.0.6 on 2024-08-21 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grau_perda', '0002_rename_configuracao_audiometrica_grauperda_grau_perda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grauperda',
            name='grau_perda',
            field=models.CharField(max_length=40, verbose_name='Grau de perda auditiva'),
        ),
        migrations.AlterField(
            model_name='grauperda',
            name='media_frequencias',
            field=models.CharField(max_length=15, verbose_name='Média entre as frequências de 500 Hz, 1 kHz, 2 kHz e 4 kHz'),
        ),
    ]
