# Generated by Django 5.0.6 on 2024-08-21 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classificacao_iprf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classificacaoiprf',
            name='dificuldade',
            field=models.CharField(max_length=100, verbose_name='Dificuldade de compreensão da fala'),
        ),
        migrations.AlterField(
            model_name='classificacaoiprf',
            name='resultado',
            field=models.CharField(max_length=20, verbose_name='Resultado de IPRF'),
        ),
    ]
