# Generated by Django 5.0.6 on 2024-07-31 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReflexoAcustico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('P', 'Presente'), ('A', 'Ausente')], max_length=1)),
                ('descricao', models.CharField(max_length=80)),
                ('caracteristicas', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
