# Generated by Django 5.0.6 on 2024-08-21 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reflexo_acustico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reflexoacustico',
            name='caracteristicas',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Características'),
        ),
        migrations.AlterField(
            model_name='reflexoacustico',
            name='descricao',
            field=models.CharField(max_length=80, verbose_name='Descrição'),
        ),
    ]
