# Generated by Django 5.0.6 on 2024-06-18 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tipo_perda_auditiva', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TipoPerdaAuditiva',
            new_name='Tipo',
        ),
    ]
