# Generated by Django 5.0.6 on 2024-07-30 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Timpanograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=10)),
                ('definicao', models.CharField(max_length=100)),
                ('valor_referencia', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
