# Generated by Django 5.0.6 on 2024-08-21 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracao_audiometrica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaoaudiometrica',
            name='caracteristicas',
            field=models.TextField(max_length=200, verbose_name='Características'),
        ),
    ]
